name: Handle closing a milestone

on:
  milestone:
    types: [ closed ]

jobs:
  build-release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: write

    steps:
      - name: Verify Milestone Name
        run: |
          if [[ ! "${{ github.event.milestone.title }}" =~ ^[a-zA-Z0-9_\.\-]+$ ]]; then
            echo "Name '${{ github.event.milestone.title }}' is not valid"
            echo "It should only contain letters (a-z & A-Z), numbers (0-9), periods (.), dashes (-) and underscores (_)"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up GraalVM JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: graalvm
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle (shadowJar + javadocJar + sourcesJar)
        env:
          GITHUB_SHA: ${{ github.sha }}
          MILESTONE_TITLE: ${{ github.event.milestone.title }}
        run: ./gradlew shadowJar javadocJar sourcesJar --no-daemon --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: NiveriaHolograms-${{ github.event.milestone.title }}
          path: build/libs/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.milestone.title }}
          name: Release ${{ github.event.milestone.title }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          make_latest: true
          body: |
            # Update ${{ github.event.milestone.title }}
            
            ${{ github.event.milestone.description }}
          files: build/libs/**
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}